# Generated by Django 4.2 on 2023-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[(1, 'Tecnología'), (2, 'Ciencia'), (3, 'Arte y cultura'), (4, 'Historia')], max_length=30),
        ),
    ]
